### ISSUE TITLE
Wormbot stuck in one axis

### ISSUE THREAD

**Issue by KileyJH** [evilxsystems/wormbot#1]
Hi, 

We are having issues in the Vidal-Gadea lab with our Wormbot. The bot is stuck in the top row and is only moving left or right. It seems to run the experiment and take images, but doesn't move up or down at all so the images are only in one row. We turned off the motors, moved it to home, then turned the motors on before resetting the robot and it went back to the top row and hasn't moved down again. 

Thanks for your help

**Comment by JasonNPitt** [comment]
Since the motors work when you manually reset the position it makes me think that for some reason your X max limit switch (the one on the transilluminator arm) is being read as closed.  
Did you change anything in the software before this happened?

Inspect the switches on the camera head and if one is bad (ie. bent and always closed) fix it or replace it.  Alternatively check the wiring to the camera head, especially that "flying circuit board" that connects the limit switches to make sure none of the wires or contacted are shorted.  If that doesn't work I can give you some steps to troubleshoot the switch

**Comment by KileyJH** [comment]
Hi Jason-

We checked all of the switches and nothing is bent or closed. The wiring all is connected, however we are not sure how to check that the contacts are shorted (nothing looks like it was burnt though). 

As always, appreciate your help!

**Comment by KileyJH** [comment]
Is there a way that we can do a fresh install that way we can be sure nothing was changed in our software?

**Comment by JasonNPitt** [comment]
yes you can do a fresh install but unless you had altered the firmware there isn't anything else in the code that should cause this behavior.  The first thing to do is to turn on the limit switch debugging in the firmware so that you can see what is going on.  Go through the steps in this document to open up the firmware http://wormbot.org/documentation/2.pdf

then remove the comment " /* " on line #346 and " */ " on line #351, save it, recompile the code and upload the code to the robot, then open the arduino serial monitor, as described in section on Manually configuring the platecoordinates.dat file (here: http://wormbot.org/documentation/9.pdf ) and examine what the robot is displaying in the serial window.  I'm guessing that your limit switch is broken.

**Comment by KileyJH** [comment]
![image](https://user-images.githubusercontent.com/57646998/68791494-0ff1c380-060f-11ea-809c-ab6e7c07c318.png)


We went ahead and recompiled the firmware without problems. When we uploaded to the robot though we got a couple of error messages on the arduino sketchbook (see above). The serial monitor kept printing 0, 0, and RR (after putting it in newline). This was after placing the robot in the real home position and hitting reset on the arduino itself.

**Comment by JasonNPitt** [comment]
you are having trouble uploading the new firmware.  Verify that you have selected Arduino Uno as the board type:
![image](https://user-images.githubusercontent.com/3652780/68792464-3bb97d00-0600-11ea-9820-6cc9efeedb3f.png)

**Comment by JasonNPitt** [comment]
if that wasn't the issue, it sounds like your bootloader may have gotten corrupted...there are ways to fix it, but the easiest way to deal with it is to just buy a new board and reflash the firmware, and swap it out for the one with the corrupted bootloader

https://www.amazon.com/Makeblock-Orion-Base-Arduino-UNO/dp/B00W6Y0PGC

or see here:
http://somedisassemblyrequired.com/index.php/2017/06/26/arduino-verification-error/

**Comment by KileyJH** [comment]
We have the arduino uno board selected and the ttyUSB0 port selected before verifying and uploading the code. We still get this error.  This time we saved the changes to the code first before verifying and uploading but got the same errors.
![Screenshot from 2019-11-13 13-03-37](https://user-images.githubusercontent.com/57646998/68795467-a675b300-0616-11ea-917a-148397361a90.png)
![Screenshot from 2019-11-13 13-05-21](https://user-images.githubusercontent.com/57646998/68795470-a83f7680-0616-11ea-8081-775bb7696891.png)

**Comment by JasonNPitt** [comment]
Ok...that probably means the bootloader got corrupted for some reason.  I've never encountered this issue, but it appears it happens sometimes due to voltage fluctuations.  If the firmware got corrupted somehow this would also explain the issues with the arm.  The quickest way to fix this would be to get a new Orion board , flash the firmware and swap it out.  You can repair the bootloader code later on the removed board

**Comment by KileyJH** [comment]
Hi Jason, 

Thanks for all of your help!

We purchased and installed a new arduino today, and have stopped receiving the error code. However now when we run the serial monitor with the switch debugging on we continuously receive the same output (attached) 
![image](https://user-images.githubusercontent.com/57646998/69171617-ed095880-0ac1-11ea-99a3-a16fb63a7ed9.png)

**Comment by JasonNPitt** [comment]
Well we are getting somewhere. It should be physically impossible for both your xmax and xmin limit switches to be pressed simultaneously, so this is your issue.  Turn off the stepper motors (slide switch on the Orion) move the arm to the center of the stage and see what the serial monitor output shows.  If it's still showing the limit switch being pressed for one of the axes, unplug the RJ25 cable from port 6 on the Orion board. That should stop it. Plug it back in and then unplug the molex connectors on the little "flying" circuit board and monitor the output.  The most likely explanation is that the switch has gone bad which would show it as stopping when you unplug the molex connector for that switch, but it's also possible that there is a short circuit on the little circuit board or in the wiring to the switch.  To verify it's the switch unplug the wires from the switch itself and monitor the output, also make sure the wires haven't just come off at the switch itself and shorted out on the chassis.

**Comment by KileyJH** [comment]
We saw the same thing again after moving to the center and tried removing the pot 6. This caused the robot to stutter in the back corner (kept moving backward when it shouldn't). We then replaced the cable and hit reset and we are not getting the following output.

![image](https://user-images.githubusercontent.com/57646998/69177057-76be2380-0acc-11ea-992c-5bd864ca2d69.png)

**Comment by KileyJH** [comment]
We also replaced the flying circuit board with a spare that we had and got the same
![Screenshot from 2019-11-19 13-05-15](https://user-images.githubusercontent.com/57646998/69177616-796d4880-0acd-11ea-9c96-b93c3f0abd3f.png)
 output

**Comment by JasonNPitt** [comment]
I did not say to turn the stepper motors back on with the RJ25 cable uninstalled...which would of course do what you observed happen and could damage the robot.

1. turn off the stepper motors
2. move the arm so that the camera is in the center of the stage and so none of the limit switches should be closed.
3. open the serial monitor and take a screenshot and send it here

**Comment by JasonNPitt** [comment]
please take a picture of the limit switches on the camera head and post it here...make certain it shows the wiring connections

**Comment by KileyJH** [comment]
Hi Jason-

The wormbot is only printing into the serial monitor once it stops moving, so when we try to put it in the center and open the serial monitor to take a photo it is empty. 

I have attached an image of the camera head 
![image](https://user-images.githubusercontent.com/57646998/69186961-34eaa880-0adf-11ea-87ec-1a0d5166f3b3.png)

**Comment by JasonNPitt** [comment]
can you get a picture from a better angle where I can see the wire connectors better?  I'm 95% sure that's where your problem is...

Sorry, i forgot the robot has to go through it's calibration routine before it enters the main loop where that switch debugging stuff is.  To make it think it went through the calibration with the motors off press the limit switches in the sequence xmin, ymin, xmax, ymax, xmin, ymin...it should go then print a confirm message RR to Serial monitor, and the limit switch code should be active.

**Comment by JasonNPitt** [comment]
also the way you guys made that limit switch assembly did not follow my design

**Comment by KileyJH** [comment]
Yeah we noticed trying to get a good picture that things were a bit backwards. We took the camera off to get a good image and saw that one of the wires was touching a bolt, shorting the wire. We moved this and are now getting the RR from serial monitor. It went through the calibration steps on its own

![image](https://user-images.githubusercontent.com/57646998/69189112-65344600-0ae3-11ea-8230-1a4993f2308b.png)

**Comment by JasonNPitt** [comment]
Ok...that was the problem...make sure that wire insulation is secure so that it doesn't slip off those leads and short to the bolts...flipping the bolts in the other way should give you less area to avoid shorts. Redownload the unmodified firmware from github and reflash to get rid of the switch debugging stuff and you should be up and running again.

**Comment by KileyJH** [comment]
We secured the insulation and switched the bolts- I'm betting that is what was drawing energy from the bootloader too. Thanks for all your help as always!
